---
- name: "Ensure packet redirect sending is disabled"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: "present"
      reload: true
      ignoreerrors: true
  with_items:
    - name: "net.ipv4.conf.all.send_redirects"
      value: "0"
    - name: "net.ipv4.conf.default.send_redirects"
      value: "0"
  notify:
      - sysctl flush ipv4 route table

- name: "Ensure source routed packets are not accepted"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: "present"
      reload: true
      ignoreerrors: true
  with_items:
    - name: "net.ipv4.conf.all.accept_source_route"
      value: "0"
    - name: "net.ipv4.conf.default.accept_source_route"
      value: "0"
  notify:
      - sysctl flush ipv4 route table

- name: "Ensure ICMP redirects are not accepted"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: "present"
      reload: true
      ignoreerrors: true
  with_items:
    - name: "net.ipv4.conf.all.accept_redirects"
      value: "0"
    - name: "net.ipv4.conf.default.accept_redirects"
      value: "0"
  notify:
      - sysctl flush ipv4 route table

- name: "Ensure secure ICMP redirects are not accepted"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: "present"
      reload: true
      ignoreerrors: true
  with_items:
    - name: "net.ipv4.conf.all.secure_redirects"
      value: "0"
    - name: "net.ipv4.conf.default.secure_redirects"
      value: "0"
  notify:
      - sysctl flush ipv4 route table

- name: "Ensure suspicious packets are logged"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: "present"
      reload: true
      ignoreerrors: true
  with_items:
    - name: "net.ipv4.conf.all.log_martians"
      value: "1"
    - name: "net.ipv4.conf.default.log_martians"
      value: "1"
  notify:
      - sysctl flush ipv4 route table

- name: "Ensure broadcast ICMP requests are ignored"
  sysctl:
      name: "net.ipv4.icmp_echo_ignore_broadcasts"
      value: "1"
      state: "present"
      reload: true
      ignoreerrors: true
  notify:
      - sysctl flush ipv4 route table

- name: "Ensure bogus ICMP responses are ignored"
  sysctl:
      name: "net.ipv4.icmp_ignore_bogus_error_responses"
      value: "1"
      state: "present"
      reload: true
      ignoreerrors: true
  notify:
      - sysctl flush ipv4 route table

- name: "Ensure Reverse Path Filtering is enabled"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: "present"
      reload: true
      ignoreerrors: true
  with_items:
    - name: "net.ipv4.conf.all.rp_filter"
      value: "1"
    - name: "net.ipv4.conf.default.rp_filter"
      value: "1"
  notify:
      - sysctl flush ipv4 route table


- name: "Ensure TCP SYN Cookies is enabled"
  sysctl:
      name: "net.ipv4.tcp_syncookies"
      value: "1"
      state: "present"
      reload: true
      ignoreerrors: true
  notify:
      - sysctl flush ipv4 route table

- name: "Ensure IPv6 router advertisements are not accepted"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: "present"
      reload: true
      ignoreerrors: true
  with_items:
    - name: "net.ipv6.conf.all.accept_ra"
      value: "0"
    - name: "net.ipv6.conf.default.accept_ra"
      value: "0"
  notify:
      - sysctl flush ipv6 route table

- name: "Ensure IPv6 redirects are not accepted"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: "present"
      reload: true
      ignoreerrors: true
  with_items:
    - name: "net.ipv6.conf.all.accept_redirects"
      value: "0"
    - name: "net.ipv6.conf.default.accept_redirects"
      value: "0"
  notify:
      - sysctl flush ipv6 route table

- name: "Ensure core dumps are restricted"
  lineinfile:
    state: "present"
    dest: "/etc/security/limits.conf"
    regexp: '^#?\\*.*core'
    line: '*                hard    core            0'
    insertbefore: '^# End of file'

- name: "Ensure core dumps are restricted"
  sysctl:
    name: "fs.suid_dumpable"
    value: "0"
    state: "present"
    reload: "true"
    sysctl_set: "true"
    ignoreerrors: "true"

- name: "Ensure address space layout randomization (ASLR) is enabled"
  sysctl:
    name: "kernel.randomize_va_space"
    value: "2"
    state: "present"
    reload: "true"
    sysctl_set: "true"
    ignoreerrors: "true"

